# Generated by Django 5.0 on 2024-01-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0009_genericpage_banner_image_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='generic.author'),
        ),
    ]
