# Generated by Django 5.0 on 2024-01-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0010_author_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
