# Generated by Django 4.2.7 on 2023-12-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Testing as New Title', max_length=100),
        ),
    ]
