# Generated by Django 4.2.7 on 2023-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Welcome to my homepage!', max_length=100),
        ),
    ]
