# Generated by Django 5.0 on 2024-01-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='Instragram',
            new_name='instagram',
        ),
    ]
