# Generated by Django 5.0 on 2024-01-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_socialmediasettings_instagram_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram_icon',
        ),
    ]
