# Generated by Django 5.0 on 2024-01-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_socialmediasettings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='image',
            new_name='instagram_icon',
        ),
    ]
