# Generated by Django 5.0 on 2024-01-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_rename_image_socialmediasettings_instagram_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='instagram_icon',
            new_name='image',
        ),
    ]
