# Generated by Django 5.0 on 2024-01-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_rename_instagram_icon_socialmediasettings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='image',
            new_name='instagramIcon',
        ),
    ]
