# Generated by Django 5.0 on 2024-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_socialmediasettings_facebook_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
