# Generated by Django 5.0 on 2024-01-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_socialmediasettings_facebook'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='instagramIcon',
            new_name='instagram_icon',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
